#!/usr/bin/env bash
set -euo pipefail
: "${DATA_ROOT:?Set DATA_ROOT=/path/to/datasets}"
: "${PYTHON:=python3}"
: "${RUN_STAMP:=$(date +%Y%m%d_%H%M%S)}"

mkdir -p revision_materials/logs/w3_headcount_h1_ramp100 && $PYTHON main.py --root_path ${DATA_ROOT} --backbone ViT-B/16 --encoder both --position all --params q k v --n_iters 500 --batch_size 32 --ramp_up_steps 100 --loss_fn ce --ortho_reduction mean --dataset eurosat --shots 4 --seed 1 --adapter ohsinglora --num_heads 1 --r 2 --lambda_o 0.0 --save_path revision_materials/checkpoints/w3_headcount_h1_ramp100 --filename eurosat_4shot_seed1_val_ohsinglora_h1_r2_lo0p0_ramp100 --run_manifest revision_materials/results/w3_headcount_h1_ramp100_results.jsonl --selection_split val --sweep_mode 2>&1 | tee revision_materials/logs/w3_headcount_h1_ramp100/eurosat_4shot_seed1_val_ohsinglora_h1_r2_lo0p0_ramp100_${RUN_STAMP}.log
mkdir -p revision_materials/logs/w3_headcount_h1_ramp100 && $PYTHON main.py --root_path ${DATA_ROOT} --backbone ViT-B/16 --encoder both --position all --params q k v --n_iters 500 --batch_size 32 --ramp_up_steps 100 --loss_fn ce --ortho_reduction mean --dataset eurosat --shots 4 --seed 2 --adapter ohsinglora --num_heads 1 --r 2 --lambda_o 0.0 --save_path revision_materials/checkpoints/w3_headcount_h1_ramp100 --filename eurosat_4shot_seed2_val_ohsinglora_h1_r2_lo0p0_ramp100 --run_manifest revision_materials/results/w3_headcount_h1_ramp100_results.jsonl --selection_split val --sweep_mode 2>&1 | tee revision_materials/logs/w3_headcount_h1_ramp100/eurosat_4shot_seed2_val_ohsinglora_h1_r2_lo0p0_ramp100_${RUN_STAMP}.log
mkdir -p revision_materials/logs/w3_headcount_h1_ramp100 && $PYTHON main.py --root_path ${DATA_ROOT} --backbone ViT-B/16 --encoder both --position all --params q k v --n_iters 500 --batch_size 32 --ramp_up_steps 100 --loss_fn ce --ortho_reduction mean --dataset eurosat --shots 4 --seed 3 --adapter ohsinglora --num_heads 1 --r 2 --lambda_o 0.0 --save_path revision_materials/checkpoints/w3_headcount_h1_ramp100 --filename eurosat_4shot_seed3_val_ohsinglora_h1_r2_lo0p0_ramp100 --run_manifest revision_materials/results/w3_headcount_h1_ramp100_results.jsonl --selection_split val --sweep_mode 2>&1 | tee revision_materials/logs/w3_headcount_h1_ramp100/eurosat_4shot_seed3_val_ohsinglora_h1_r2_lo0p0_ramp100_${RUN_STAMP}.log
mkdir -p revision_materials/logs/w3_headcount_h1_ramp100 && $PYTHON main.py --root_path ${DATA_ROOT} --backbone ViT-B/16 --encoder both --position all --params q k v --n_iters 500 --batch_size 32 --ramp_up_steps 100 --loss_fn ce --ortho_reduction mean --dataset eurosat --shots 4 --seed 1 --adapter ohsinglora --num_heads 1 --r 4 --lambda_o 0.0 --save_path revision_materials/checkpoints/w3_headcount_h1_ramp100 --filename eurosat_4shot_seed1_val_ohsinglora_h1_r4_lo0p0_ramp100 --run_manifest revision_materials/results/w3_headcount_h1_ramp100_results.jsonl --selection_split val --sweep_mode 2>&1 | tee revision_materials/logs/w3_headcount_h1_ramp100/eurosat_4shot_seed1_val_ohsinglora_h1_r4_lo0p0_ramp100_${RUN_STAMP}.log
mkdir -p revision_materials/logs/w3_headcount_h1_ramp100 && $PYTHON main.py --root_path ${DATA_ROOT} --backbone ViT-B/16 --encoder both --position all --params q k v --n_iters 500 --batch_size 32 --ramp_up_steps 100 --loss_fn ce --ortho_reduction mean --dataset eurosat --shots 4 --seed 2 --adapter ohsinglora --num_heads 1 --r 4 --lambda_o 0.0 --save_path revision_materials/checkpoints/w3_headcount_h1_ramp100 --filename eurosat_4shot_seed2_val_ohsinglora_h1_r4_lo0p0_ramp100 --run_manifest revision_materials/results/w3_headcount_h1_ramp100_results.jsonl --selection_split val --sweep_mode 2>&1 | tee revision_materials/logs/w3_headcount_h1_ramp100/eurosat_4shot_seed2_val_ohsinglora_h1_r4_lo0p0_ramp100_${RUN_STAMP}.log
mkdir -p revision_materials/logs/w3_headcount_h1_ramp100 && $PYTHON main.py --root_path ${DATA_ROOT} --backbone ViT-B/16 --encoder both --position all --params q k v --n_iters 500 --batch_size 32 --ramp_up_steps 100 --loss_fn ce --ortho_reduction mean --dataset eurosat --shots 4 --seed 3 --adapter ohsinglora --num_heads 1 --r 4 --lambda_o 0.0 --save_path revision_materials/checkpoints/w3_headcount_h1_ramp100 --filename eurosat_4shot_seed3_val_ohsinglora_h1_r4_lo0p0_ramp100 --run_manifest revision_materials/results/w3_headcount_h1_ramp100_results.jsonl --selection_split val --sweep_mode 2>&1 | tee revision_materials/logs/w3_headcount_h1_ramp100/eurosat_4shot_seed3_val_ohsinglora_h1_r4_lo0p0_ramp100_${RUN_STAMP}.log
mkdir -p revision_materials/logs/w3_headcount_h1_ramp100 && $PYTHON main.py --root_path ${DATA_ROOT} --backbone ViT-B/16 --encoder both --position all --params q k v --n_iters 500 --batch_size 32 --ramp_up_steps 100 --loss_fn ce --ortho_reduction mean --dataset caltech101 --shots 4 --seed 1 --adapter ohsinglora --num_heads 1 --r 2 --lambda_o 0.0 --save_path revision_materials/checkpoints/w3_headcount_h1_ramp100 --filename caltech101_4shot_seed1_val_ohsinglora_h1_r2_lo0p0_ramp100 --run_manifest revision_materials/results/w3_headcount_h1_ramp100_results.jsonl --selection_split val --sweep_mode 2>&1 | tee revision_materials/logs/w3_headcount_h1_ramp100/caltech101_4shot_seed1_val_ohsinglora_h1_r2_lo0p0_ramp100_${RUN_STAMP}.log
mkdir -p revision_materials/logs/w3_headcount_h1_ramp100 && $PYTHON main.py --root_path ${DATA_ROOT} --backbone ViT-B/16 --encoder both --position all --params q k v --n_iters 500 --batch_size 32 --ramp_up_steps 100 --loss_fn ce --ortho_reduction mean --dataset caltech101 --shots 4 --seed 2 --adapter ohsinglora --num_heads 1 --r 2 --lambda_o 0.0 --save_path revision_materials/checkpoints/w3_headcount_h1_ramp100 --filename caltech101_4shot_seed2_val_ohsinglora_h1_r2_lo0p0_ramp100 --run_manifest revision_materials/results/w3_headcount_h1_ramp100_results.jsonl --selection_split val --sweep_mode 2>&1 | tee revision_materials/logs/w3_headcount_h1_ramp100/caltech101_4shot_seed2_val_ohsinglora_h1_r2_lo0p0_ramp100_${RUN_STAMP}.log
mkdir -p revision_materials/logs/w3_headcount_h1_ramp100 && $PYTHON main.py --root_path ${DATA_ROOT} --backbone ViT-B/16 --encoder both --position all --params q k v --n_iters 500 --batch_size 32 --ramp_up_steps 100 --loss_fn ce --ortho_reduction mean --dataset caltech101 --shots 4 --seed 3 --adapter ohsinglora --num_heads 1 --r 2 --lambda_o 0.0 --save_path revision_materials/checkpoints/w3_headcount_h1_ramp100 --filename caltech101_4shot_seed3_val_ohsinglora_h1_r2_lo0p0_ramp100 --run_manifest revision_materials/results/w3_headcount_h1_ramp100_results.jsonl --selection_split val --sweep_mode 2>&1 | tee revision_materials/logs/w3_headcount_h1_ramp100/caltech101_4shot_seed3_val_ohsinglora_h1_r2_lo0p0_ramp100_${RUN_STAMP}.log
mkdir -p revision_materials/logs/w3_headcount_h1_ramp100 && $PYTHON main.py --root_path ${DATA_ROOT} --backbone ViT-B/16 --encoder both --position all --params q k v --n_iters 500 --batch_size 32 --ramp_up_steps 100 --loss_fn ce --ortho_reduction mean --dataset caltech101 --shots 4 --seed 1 --adapter ohsinglora --num_heads 1 --r 4 --lambda_o 0.0 --save_path revision_materials/checkpoints/w3_headcount_h1_ramp100 --filename caltech101_4shot_seed1_val_ohsinglora_h1_r4_lo0p0_ramp100 --run_manifest revision_materials/results/w3_headcount_h1_ramp100_results.jsonl --selection_split val --sweep_mode 2>&1 | tee revision_materials/logs/w3_headcount_h1_ramp100/caltech101_4shot_seed1_val_ohsinglora_h1_r4_lo0p0_ramp100_${RUN_STAMP}.log
mkdir -p revision_materials/logs/w3_headcount_h1_ramp100 && $PYTHON main.py --root_path ${DATA_ROOT} --backbone ViT-B/16 --encoder both --position all --params q k v --n_iters 500 --batch_size 32 --ramp_up_steps 100 --loss_fn ce --ortho_reduction mean --dataset caltech101 --shots 4 --seed 2 --adapter ohsinglora --num_heads 1 --r 4 --lambda_o 0.0 --save_path revision_materials/checkpoints/w3_headcount_h1_ramp100 --filename caltech101_4shot_seed2_val_ohsinglora_h1_r4_lo0p0_ramp100 --run_manifest revision_materials/results/w3_headcount_h1_ramp100_results.jsonl --selection_split val --sweep_mode 2>&1 | tee revision_materials/logs/w3_headcount_h1_ramp100/caltech101_4shot_seed2_val_ohsinglora_h1_r4_lo0p0_ramp100_${RUN_STAMP}.log
mkdir -p revision_materials/logs/w3_headcount_h1_ramp100 && $PYTHON main.py --root_path ${DATA_ROOT} --backbone ViT-B/16 --encoder both --position all --params q k v --n_iters 500 --batch_size 32 --ramp_up_steps 100 --loss_fn ce --ortho_reduction mean --dataset caltech101 --shots 4 --seed 3 --adapter ohsinglora --num_heads 1 --r 4 --lambda_o 0.0 --save_path revision_materials/checkpoints/w3_headcount_h1_ramp100 --filename caltech101_4shot_seed3_val_ohsinglora_h1_r4_lo0p0_ramp100 --run_manifest revision_materials/results/w3_headcount_h1_ramp100_results.jsonl --selection_split val --sweep_mode 2>&1 | tee revision_materials/logs/w3_headcount_h1_ramp100/caltech101_4shot_seed3_val_ohsinglora_h1_r4_lo0p0_ramp100_${RUN_STAMP}.log
